# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qatd_cpp_is_overlap <- function(x1_, y1_, w1_, h1_, boxe_) {
    .Call(`_quanteda_textplots_qatd_cpp_is_overlap`, x1_, y1_, w1_, h1_, boxe_)
}

